DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'reporting') THEN
        CREATE SCHEMA reporting;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS reporting."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'reporting') THEN
        CREATE SCHEMA reporting;
    END IF;
END $EF$;

CREATE TABLE reporting.audit_entries (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Action" character varying(100) NOT NULL,
    "UserId" bigint,
    "Details" text NOT NULL,
    "Signature" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_audit_entries" PRIMARY KEY ("Id")
);

CREATE TABLE reporting.tax_reports (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AccountId" bigint NOT NULL,
    "Year" integer NOT NULL,
    "Status" character varying(50) NOT NULL,
    "DownloadUrl" text,
    "Signature" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_tax_reports" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_audit_entries_UserId" ON reporting.audit_entries ("UserId");

CREATE INDEX "IX_tax_reports_AccountId_Year" ON reporting.tax_reports ("AccountId", "Year");

INSERT INTO reporting."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260904232346_InitialReporting', '8.0.30');

COMMIT;

START TRANSACTION;

DROP TABLE reporting.tax_reports;

CREATE TABLE reporting.tax_reports (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" bigint NOT NULL,
    "AccountId" bigint NOT NULL,
    "TaxYear" integer NOT NULL,
    "TotalInterestMinor" bigint NOT NULL,
    "TaxDeductedMinor" bigint NOT NULL,
    "Currency" character varying(3) NOT NULL,
    "CustomerName" character varying(200) NOT NULL,
    "AccountNumber" character varying(50) NOT NULL,
    "AccountName" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "SchemaVersion" character varying(20) NOT NULL,
    "PayloadHash" character varying(64) NOT NULL,
    CONSTRAINT "PK_tax_reports" PRIMARY KEY ("Id")
);

CREATE TABLE reporting.tax_report_documents (
    "TaxReportId" bigint NOT NULL,
    "DocumentId" bigint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_tax_report_documents" PRIMARY KEY ("TaxReportId", "DocumentId"),
    CONSTRAINT "FK_tax_report_documents_tax_reports_TaxReportId" FOREIGN KEY ("TaxReportId") REFERENCES reporting.tax_reports ("Id") ON DELETE RESTRICT
);

CREATE TABLE reporting.tax_report_jobs (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TaxReportId" bigint NOT NULL,
    "Status" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_tax_report_jobs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tax_report_jobs_tax_reports_TaxReportId" FOREIGN KEY ("TaxReportId") REFERENCES reporting.tax_reports ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_tax_reports_AccountId_TaxYear" ON reporting.tax_reports ("AccountId", "TaxYear");

CREATE INDEX "IX_audit_entries_Action" ON reporting.audit_entries ("Action");

CREATE INDEX "IX_audit_entries_CreatedAt" ON reporting.audit_entries ("CreatedAt");

CREATE INDEX "IX_audit_entries_UserId_CreatedAt" ON reporting.audit_entries ("UserId", "CreatedAt");

CREATE INDEX "IX_tax_report_documents_DocumentId" ON reporting.tax_report_documents ("DocumentId");

CREATE INDEX "IX_tax_report_jobs_Status_CreatedAt" ON reporting.tax_report_jobs ("Status", "CreatedAt");

CREATE INDEX "IX_tax_report_jobs_TaxReportId" ON reporting.tax_report_jobs ("TaxReportId");

INSERT INTO reporting."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261006043641_AddAnnualTaxReportFlow', '8.0.30');

COMMIT;

START TRANSACTION;

ALTER TABLE reporting.tax_reports ADD "AuthorityReference" character varying(100);

ALTER TABLE reporting.tax_reports ADD "ReportedAt" timestamp with time zone;

ALTER TABLE reporting.tax_reports ADD "ReportingAuthority" character varying(100);

ALTER TABLE reporting.tax_reports ADD "ReportingStatus" character varying(30) NOT NULL DEFAULT 'NotReported';

INSERT INTO reporting."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261006093529_AddTaxReportAuthorityFields', '8.0.30');

COMMIT;

