<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="6.0.11" />
  </ItemGroup>

  <ItemGroup Condition="Exists('../../native/pdf_generator/build/libnordiska_document_c_api.so')">
    <None Include="../../native/pdf_generator/build/libnordiska_document_c_api.so"
          Link="libnordiska_document_c_api.so"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
