<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Banking\Nordiska.Modules.Banking.csproj" />
    <ProjectReference Include="..\Modules\Faq\Nordiska.Modules.Faq.csproj" />
    <ProjectReference Include="..\Modules\Reporting\Nordiska.Modules.Reporting.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0376a5cb-ee2a-4b9c-b42a-c12b974709d8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>
            runtime; build; native; contentfiles; analyzers; buildtransitive
        </IncludeAssets>
    </PackageReference>
  </ItemGroup>



</Project>
